### ISSUE TITLE
using the inexor/ prefix in includes

### ISSUE THREAD

**Issue by koraa** [inexor-game/code#107]
At the moment, when we include something from inexor, we can use the following scheme:

  ```#include "NAMESPACE/FILE"```

This might introduce some dangers of collision, so I am contemplating, whether we should use a more canonical scheme:

  ```#include "inexor/NAMESPACE/FILE"```

This would make collisions a lot less probably and it would cause the namespace names and the includes to be better in sync:

  ```c++
  #include "inexor/util/util.h"
  
  using namespace inexor::util;
  ```

To achieve this we would need to rename the `src/` folder to `inexor/` and we would need to add the project root to the include dirs.
For the time being this should probably be optional, because lot's of old sb code would need to be refactored in order to enforce this style.

What do you thing?

**Comment by koraa** [comment]
Could you please give mee feedback for this?

**Comment by a-teammate** [comment]
Although your concerns may be reasonable, "might introduce" is a bit vague for me.
I think if we do a major change (and renaming the whole source tree is a major step) it should happen for more than the possible scenario that we are about to use a lib which places its includes inside a "rpc" "net" or "ui" folder..

But honestly: if a lib uses such a bad naming scheme, we shouldn't use it. Since that is highly probably not going to be their only flaw. (Good naming for a global lib: "enet/enet.h" bad naming: "net/enet.h")
So if those libs are designed to create clashes... well .. not our business, isnt it?

**Comment by koraa** [comment]
It is not really vague: We have a definite collision already – net/ is used by some linux standard headers.

Then using interface/ or networking/ as the name of our modules would not be much better, because those are still generic names.
net/ is as generic as networking/; net/ was probably choosen/ because sys devs like it short.

And I agree with you, prefixing using enet/ instead of net/ is pretty good, because all the headers were prefixed with the project name – which is exactly what I am trying to do; we are merely using one more level of nesting because inexor is relatively complex.

**Comment by koraa** [comment]
Merged
