### ISSUE TITLE
One click build

### ISSUE THREAD

**Issue by koraa** [inexor-game/code#120]
We should provide a script that automates the entire build process, including testing, creating subdirs and checking out submodules.

**Comment by koraa** [comment]
This should provide *very verbose* messages of what's missing and optimally auto install the required packages.

**Comment by IAmNotHanni** [comment]
I think the situation got better now. We just have to convince new developers of the capabilities of CMake and Git.

**Comment by Croydon** [comment]
I don't think such a script could be done within a reasonable time <-> effort relation. The possibilities of environments with different OS(-version), compiler(-versions), CMake versions, Git versions are just too many.

Also I don't think the building steps are too complex, most of the time people struggle because they are new to Git or because of differences on their OS in comparison to our environment.

**Comment by DarkDeepBlue** [comment]
As a new developer who is familiar with cmake and git, my biggist problem was that there is no clear set of instructions how to connect the data repository with the code repository. Although one could actually write a platform-more-or-less-independant python script for example, I think that it’s more important to provide accurate instructions in the wiki.

Also, as structural changes are planned, it wouldn't make sense to write such a script at this exact stage.

**Comment by koraa** [comment]
IMHO, we should provide such instructions, but get rid of the existing one click build script

**Comment by Croydon** [comment]
> IMHO, we should provide such instructions, but get rid of the existing one click build script
+1

However, this issue isn't even about the current one, it's about expending its capabilities. So I guess we can say we won't do this one.

Also the current script wasn't maintained anyway. So lets get rid of it.
