### ISSUE TITLE
Use a alternate standard port

### ISSUE THREAD

**Issue by Fohlen** [inexor-game/code#193]
We should change the alternate standard port 28785 from sauerbraten.
Anyone has a suggestion?

**Comment by a-teammate** [comment]
pick a number you like and check whether its available ( http://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?&page=125 )

keep in mind that we need multiple ports for serverinfo, masterserver, stdport .. but maybe we dont need them all in the same region (like they are used to be, but that makes them immemorizeable)?

the numbers should be:
* easy to remember
* easy to remember
* good looking
* easy to remember

what about the area 31000-31019? which is yet "unassigned" (officially).

e.g. 31000 for the stdserver port and 31013 for the master?
other exmaple: since the area from 41798 to 42507 is also unassigned we could also go for 42000.

**Comment by Fohlen** [comment]
42575, 42576, 42577 ?

**Comment by a-teammate** [comment]
not really easy to remember, are they? :D

suggestion: 31013 as stdport (-1 for the serverinfo port) and  for the master requests 24042 (42 the answer to everything, 13 being a rememberable number + its inverse)

**Comment by Croydon** [comment]
You don't necessary need to remember the default ports because you don't need to specify the port in the connect statement if it's the default. 
Also I guess it's better to have three sequential numbers, but the first port (for the game servers) could be ofc something fancy.

**Comment by Croydon** [comment]
I would go for either
42575, 42576, 42577
or
31000, 31001, 31002.

Other opinions?

**Comment by aschaeffer** [comment]
I suggest: 31415

1. π
2. easy to remember

**Comment by IAmNotHanni** [comment]
nice one Hanack

**Comment by Fohlen** [comment]
I think we can agree on31415 for game and 31416 for query/master port

**Comment by Croydon** [comment]
You mean 31415 for game and query and 31416 for master :)
