### ISSUE TITLE
cmake: Allow deactivating targets

### ISSUE THREAD

**Issue by koraa** [inexor-game/code#196]
It should be possible to build a specific target only (e.g. tests, client or server), thus ignoring all the libs the other service requires.

We should automatically deactivate targets, if their dependencies have not been found and report this at the end of the config.

**Comment by a-teammate** [comment]
could you please explain how this is currently not the case?
for example i can select to build the server only or the client only for visual studio as well as codeblocks with mingw.
And yes: it does build those targets only.

Furthermore we do have the option to exclude specific targets when generating project files through cmake (options BUILD_TEST, BUILD_CLIENT, BUILD_SERVER), how does this not have the desired effect?

btw this issue is a duplicate of #172

**Comment by koraa** [comment]
#172 is about not having to build all targets in order to install even if you configured for them.

But right we do have those. Nevermind. I forgot about them even though I wrote them myself ^^

Also: we have to many tickets.
