### ISSUE TITLE
Use emscripten to generate NodeJS SocketMessageConnect (...)

### ISSUE THREAD

**Issue by Fohlen** [inexor-game/code#219]
We could use [emscripten](https://github.com/kripken/emscripten) to automatically wrap IPC/SocketMessage implementations from C/C++ to NodeJS. Using this method we would reduce the hassle of adapting our protocol with every change we make in the backend.

**Comment by Fohlen** [comment]
This is actually being replaced with https://github.com/inexor-game/code/wiki/Inexor-Tree-API

**Comment by koraa** [comment]
This is *not* being replaces by the tree API. The RPC/protobuf API will still stay since the tree API will be *based* on it. The Tree API is a layer above the RPC transport.

We still can't generate that with EMscripten; maybe we could generate equivalent calls in node, but the low level APIs used for networking are just completely different; we would either need to have an ASIO implementation in pure node or we woulld need to also translate ASIO and somehow be able to access low level syscalls to node – which I bet are not available either.

If we wanted to translate the protobuf stuff as well we'd run into a ton more problems, because protobuf for C++ is extremely tightly bound to the language C++ and to the internals of Inexor.

So even if we where somehow able to translate the C++ code I bet the translation layer we would have to build would require four or five times as much code as the current pure node implementation of that stuff, which is after all pretty short and straight forward.

**Comment by koraa** [comment]
Btw, we don't really have to adapt anything if we change something in inexor: Node.js metaprogramming is used mostly so we essentially just have to get a list of commands to support from somewhere and can automatically support these.

Same with the tree in the future: protobuf supports reflection on the protocol descriptions and we can extract a list of paths from the C++ code, so we can write a layer that automatically forwards requests given a specific path.
