### ISSUE TITLE
Ellipsis syntax in inexor/util/thread_local.h

### ISSUE THREAD

**Issue by basile-henry** [inexor-game/code#236]
I've been having some problems compiling master since this file was added: inexor/util/thread_local.h
After trying to change my compiler and changing the compiler flags to support this syntax I just tried to comment out the part that raised some errors (since it looks like from_args is never called anyway). This works for me, it now compiles. I'm just wondering what this code does and if we need to use this syntax. The first and second ellipsis aren't a problem but the third and fourth are the ones my compiler complains about.

```
     template<typename... Args>
     static thread_local_ptr<T> from_args(Args... args) {
         return new thread_local_ptr<T>([args...]() {
             return new T(args...);
         });
     }
```

**Comment by a-teammate** [comment]
thats actually part of the standard (c++11) and hence a compiler issue.
which compiler are you using? and which version?

however what i dont think theres a use for this file anymore, is it @koraa ?

**Comment by basile-henry** [comment]
By default cmake sets my C compiler to be cc and C++ compiler to be c++ but I also tried using gcc as a C compiler and g++ as a C++ compiler. Same result both times.

**Comment by koraa** [comment]
@basile-henry cc is usually gcc; if it's not gcc it's very likely clang :)

The ellipsis marks a variadic function;
it creates a thread_local_ptr with a lambda just that stores all parameters given to the function and just forwards all those parameters to thr constructor once the lambda is invoked. (The lambda is invoked to construct the underlying thread local pointer on demand),

(It's not a very good implementation though because I should have put more thought into when ther parameters are being copied and where exactly ;) ).

@a-teammate Perfectly right. it was just a workaround for windows not supporting thread_local. I've seen your branch removing that stuff again, so thanks for doing that!

@basile-henry I am afraid it would still be better if you upgraded your compiler. gcc 4.8 does not have full c++11 support; 4.9 or better yet 5.1 do. 5.1 should also have very advanced c++14 support, which is very good too!

**Comment by basile-henry** [comment]
I'm upgrading to a more recent gcc, I was trusting Ubuntu's repos to be more up to date than they actually are, thanks for the pointers. :)
