### ISSUE TITLE
Introduce a unit test framework

### ISSUE THREAD

**Issue by aschaeffer** [inexor-game/code#26]
Introduce a unit test framework

**Comment by koraa** [comment]
@IAmNotHanni Yes, that, and a framework to make it easy.

Quick research suggests one of the following libs:
* http://turtle.sourceforge.net/
* https://github.com/CxxTest/cxxtest
* http://www.boost.org/doc/libs/1_57_0/libs/test/doc/html/index.html

Any other recommendations?

**Comment by koraa** [comment]
There is also googletest: https://code.google.com/p/googletest/

**Comment by koraa** [comment]
https://code.google.com/p/googlemock/

**Comment by koraa** [comment]
https://github.com/unittest-cpp/unittest-cpp

**Comment by koraa** [comment]
http://gamesfromwithin.com/exploring-the-c-unit-testing-framework-jungle

**Comment by koraa** [comment]
http://accu.org/index.php/journals/1326

**Comment by killme** [comment]
http://www.vtk.org/Wiki/CMake/Testing_With_CTest

**Comment by koraa** [comment]
So, I am currently in the process of evaluating test frameworks. I started with ctest (https://github.com/bvdberg/ctest).

Turns out there is a difference between CMake/CTest and ctest: ctest is a testing framework, CTest allows you to add test configurations to a CMake setup, but if I am understanding this correctly you still need some test framework though - like ctest for instance.

I am going to punch whoever introduced that ambiguity.

You can find the tests I have been writing with ctest in the branch karo/unittesting or in the associated pull request: #95 . They are not done yet and not expected to work at the moment.

While I was writing these I noticed a few things:
* We do want a testing framework with c++ support, otherwise we end up with loads of macros and nasty hacks to test for c++ features like exceptions. Memory management in particular becomes awkward because C expects you to do manual memory management, C++ often don't.
* We should also be able to write generic tests for generic interfaces. Stuff like the sauerbraten streams or the models or all the different entities have similar interfaces; a player IS an fpsent, so we should just be able to run all the fpsent tests on a player!

**Comment by koraa** [comment]
I am giving upon CTest, it's just thrown 100k lines of errors; there really is no way around doing ALL memory management manually (using pointers) and it is basically written in macros.

**Comment by koraa** [comment]
sorry, I ment, I am giving up on ctest, big difference :)

**Comment by aschaeffer** [comment]
Ok, maybe we should use a framework that's integrated in jenkins?
https://wiki.jenkins-ci.org/display/JENKINS/Plugins (search for unit test)

**Comment by koraa** [comment]
@aschaeffer I think all the frameworks mentioned, besides ctest, support Jenkins

I've done a bit more research and cppunit and cpptest seem to work, but they are not very well documented and seem to be a bit lacking in terms of features (e.g. no support for parameterized tests).

Cxxtest seems to be quite powerful but depends on python.

Boost Test and google test seem to be quite feature complete, they both support parameterized tests, I think both support jenkins and there is extensive documentation on a loads of documentation i haven't yet gotten into.

Personally I think that the google test syntax and documentation appear to be a bit more concise. Besides that googletest is using CMake and throw googlemock in if we should require mocking.
Hence I'd reimplement the tests I've created until now with googletest and, if no major issues come up in that process, I'd like to adopt googletest as our testing framework.

Is everyone OK with going that way?

--

http://marlenacompton.com/?p=5

**Comment by koraa** [comment]
Done.
