### ISSUE TITLE
make install with custom DESTDIR is faulty

### ISSUE THREAD

**Issue by bebehei** [inexor-game/code#286]
Compiling as usual, but for make install, this is used: 
```
$ make DESTDIR=/tmp/inexor install`.
[...]
-- Installing: /tmp/inexor/home/bebe/code/inexor/bin/all/locales/nl.pak
[...]
```

Using a custom DESTDIR is required for correct packaging. Also your current path, where you compile inexor shouldn't change the behaviour of make install.

**Comment by a-teammate** [comment]
Could you detail the problem in context for me a bit?
Is this solving this the only solution for getting a package, or is it a saner solution or is it better behaviour on linux or sth else?

the point of having local installs is that your repo keeps it stuff for itself. 
dunno how appreciated that is on unix platforms but for me its gold, since i usually dont want global packages and such stuff on windows and ive different repos of inexor on my harddrives where i build and run stuff independently.

if u like to hack into that:
code/CMakeLists.txt -> EXE_DIR EXE_SUB_DIR and those set commands is what ure probably looking for
( change the PROJECT_SOURCE_DIR to https://cmake.org/cmake/help/v3.0/variable/CMAKE_INSTALL_PREFIX.html (but like i said, that would destroy the localiness of inexor)

**Comment by bebehei** [comment]
The current build with cmake is highly integrated into the git sourcetree. So as a dev, the current setup is quite perfect.

But to get a bigger user-basis, you don't want to make the user `git clone` and all other compilation stuffs. So we need to create packages. These are installed via `cmake && make && make DESTDIR=<your temporary package root> install`. 

To explain ... [wait I'm too lazy for this. GNU docs may help you.](https://www.gnu.org/prep/standards/html_node/DESTDIR.html)

I already searched for hints, and it led me to `PROJECT_SOURCE_DIR`, too. `PROJECT_SOURCE_DIR` may be a good thing to use, but it'll always give you the **full** path of the inexor tree. So it does matter if you clone your git-repository to `/tmp/` or have it in `$HOME` (altough it should not).

**Comment by PowerKiller** [comment]
well doesn't CMake support a kind of --prefix thingy?

**Comment by Fohlen** [comment]
@ PowerKiller, can you provide your scripts to build RPM packages on Suse, so we can test them on https://ci.b3be.de ?
We will provide an OpenSuse/Fedora (whatever we need) container to build it than!

**Comment by bebehei** [comment]
@PowerKiller Yes and No. Usually, you would fix this by using `--prefix` in Autotools. AFAIK there is no real standard in cmake to use a prefix. I've only seen other projects using something similar like `CMAKE_INSTALL_PREFIX`, but that's not a real concept. There it's just a variable representing the old concept of `--prefix`.

So, there is no configuration in `CMakeLists.txt` yet, which would respect such a variable. So I'm currently testing packages for Arch and also patching the `CMakeLists.txt`

It would be great, If you could send me your RPMs. I've got no experience with RPM based systems yet. The only thing I did, was installing Fedora last week and using CentOS for a short time years ago.

**Comment by PowerKiller** [comment]
hmm, as soon as I get my ZNC up, I'll give you the script.

**Comment by PowerKiller** [comment]
Hmmm specifying the -DCMAKE_INSTALL_PREFIX:PATH=somedir is not present in current CMake?

**Comment by PowerKiller** [comment]
So according to you, patching the lists file is the only way?

**Comment by bebehei** [comment]
@Powerkiller yes, patching the lists is the only way. The `CMakeLists.txt` is currently prepared to make builds inside the git-dir. But actually a normal user wants a package and not to build inexor by itself.

**Comment by PowerKiller** [comment]
hmm...
Install in /usr/ ?
building a package won't hurt anyway.
This will be a pain in a$$ for M$ users.
