### ISSUE TITLE
TOML instead of JSON or YAML

### ISSUE THREAD

**Issue by a-teammate** [inexor-game/code#348]
I recently spend some time figuring about right configuration file format to use.
While we already settled a bit on JSON, I think there are good alternatives:

* YAML
* TOML

The reason I started looking was the lack of comments in JSON.

The point is that our configuration files should be as easy editable for humans as possible. (Not because thats their main target, but bc the other points like having decent libraries and having reference support should already be out of question, but JSON lacks the latter)

JSON has the advantage of being tightly coupled with the JS-world.
It lacks comments and references though and hence is imo the worst of all the three for user-editable files.
YAML is too complex (something over 200 language rules, JSON has 20), TOML looks awesome.
https://github.com/toml-lang/toml#comparison-with-other-formats

The one thing which could hold us from TOML is that its not yet declared stable.  
However it is noted in their issues that there are only semi-important stuff in question until v1.0 (date and time types getting discussed and octal/hex/binary integers).
Its used by big companies already.

TOMLs nesting syntax may be a bit distracting at first (subtrees are `[tree.node1.node2]`, but if you look at YAML (which uses indentation instead for subnodes) I think TOMLs solution is less error prone:  
* Users do not have space/tabs visible in their text-editors
* YAML files are hence having a lot of lines
  * readability can't be enhanced by skipping that

So thats why I would say we should use TOML and not JSON or YAML (at least for configuration files).

some other ones are [end, fressian, transit] https://groups.google.com/forum/#!msg/clojure/9ESqyT6G5nU/2Ne9X6JBUh8J), but they go more into the direction of protobuf: compact transmitting is their focus i think. edn is the most readable of them, but it looks far from stable and far from being widely adopted.

**Comment by aschaeffer** [comment]
I don't think there's a better alternative than JSON at the moment even if JSON has it's disadvantages. But instead of comparing JSON, YAML, TOML and XML, I'd ask if a replacement of JSON is really necessary.

We are about to split CubeScript (which is a strange conglomerate of user interface + configuration + scripting) into several parts:

* Separate the user interface -> HTML + Client-Side-JavaScript + REST
* Separate the configuration -> JSON
* Separate the scripting -> Server-Side-JavaScript
* Separate the communication data -> JSON
* Separate the shaders -> Shaders language

CubeScript needed comments for scripting and for the configuration. Because scripting is done in JavaScript, the most part of commenting goes there.

For configuration files we (should) have user interfaces for that in the future. A normal user shouldn't have to edit dumb configuration files by hand. For developers commenting in configuration files could be a benefit, but I think it's not that important.

**Comment by MartinMuzatko** [comment]
What about CSON https://github.com/bevry/cson ?
Alternatively, we could have js files with JSON exports.
e.g.:

config.js
``` js
module.exports = {
    // Comments!
    property: 'value'
}
```
loading the file:
``` js
require ('./config.js')
```

**Comment by a-teammate** [comment]
@MartinMuzatko  We would need some settings to be loadable by InexorCore (the C++ side). But CSON is the same as JSON but for coffee, so it would be useful for config files which are solely saved/red in a coffeescript environment.

@aschaeffer 
What we have is the tree (on InexorFlex and InexorCore(C++) side, maybe the InexorUI can be fed with JSON, idc), inside that tree our data gets defined:
* settings, which a user could possibly edit:
   * e.g. important screen and startup settings
   * or media paths
   * and all other settings
* stuff content creators edit
   * e.g. model/texture/sound configurations
   * shader definitions see ***
* map-specific/network stuff which mainly should be handled by machine

Except for the last part it would be beneficial to be able to change stuff in a simple text editor / or your IDE.  

If I want to write for example a configuration file for a model I'd ideally only need to reference the animations and not c&p it in all places they're needed (e.g. mr fixit and snoutx share the same anims).  
In my JSON-parser I ended up trying to introducing this manually (extending/violating the standard).  But why not use a format which got them by house?*  

Having no comments is for me a show-stopper (yes JSON im looking at you), I tried so often to comment stuff (or how would you for example design an example model.json if you can't comment it in place?)._**_  

This is simply b.c. JSON is not designed to be human editable but human-readable. Its good for dumps of data you generated in your code and want to drop on the disk/send it to some other place.
Not for some user to do it by hand.  

**But why forbid it to do it by hand if there's no need to?**

We need to serialize that tree possibly in JS and in C++, so libs for both should be available. This is true for all 3 candidates (we didn't introduce JSON yet btw, or did we?).  
And although JSON is native JS, using YAML or TOMLs parsers is max 2 additional lines of code.

`*` _YAML got references, calling them anchors. TOML and JSON don't have them, they would need a list of manual references, which could mean we need to add our own logic processing the data afterwards, possibly having all kinds of bugs (e.g. loosing information through serialisation/deserialisation) and we would need to maintain multiple ones **if we do want references**. So for those it would be better to just not do that._

_`**` However you can "add comments" to JSON by just introducing fields which don't get used. But this does not always work (e.g. how to comment the root node?) and is always comparable ugly (and possibly less efficient to parse if that's a goal)_

`***` _Example:
Lets compare the 3 for (possible) shader definition files (flat structures):_
**JSON**:
```JSON
{
"name": "default-shader",
"comment": "Our vertex shader source (the first stage, acting on the vertices)",
"vertex-source": [
"    void main(void)",
"    {",
"        gl_Position = ftransform();",
"        gl_TexCoord[0] = gl_MultiTexCoord0;",
"        gl_FrontColor = gl_Color;",
"    }" ],
"comment": "Our pixel shader (aka fragment shader) is acting on the individual pixels on the object.",
"fragment-source": [
"    uniform sampler2D tex0;",
"    void main(void)",
"    {",
"        gl_FragColor = gl_Color * texture2D(tex0, gl_TexCoord[0].xy);",
"    }",],
"fallback-shaders": ["notexture-shader", "null-shader"]
}
```
**YAML**:
```yaml
name: default-shader
# Our vertex shader source (the first stage, acting on the vertices):
vertex-source: >
    void main(void)
    {
        gl_Position = ftransform();
        gl_TexCoord[0] = gl_MultiTexCoord0;
        gl_FrontColor = gl_Color;
    }
# Our pixel shader (aka fragment shader) is acting on the individual pixels on the object.
fragment-source: >
    uniform sampler2D tex0;
    void main(void)
    {
        gl_FragColor = gl_Color * texture2D(tex0, gl_TexCoord[0].xy);
    }
fallback-shaders: ["notexture-shader", "null-shader"]
```
**TOML**:
```toml
name = "default-shader"
# Our vertex shader source (the first stage, acting on the vertices):
vertex-source = '''
    void main(void)
    {
        gl_Position = ftransform();
        gl_TexCoord[0] = gl_MultiTexCoord0;
        gl_FrontColor = gl_Color;
    }'''
# Our pixel shader (aka fragment shader) is acting on the individual pixels on the object.
fragment-source = '''
    uniform sampler2D tex0;
    void main(void)
    {
        gl_FragColor = gl_Color * texture2D(tex0, gl_TexCoord[0].xy);
    }'''
fallback-shaders = ["notexture-shader", "null-shader"]
``` 
_Some notes on these:
* JSON line endings are not covered by rules
  * You need this [ "    ", "    "] workaround 
  * but sure one would just create a distinct file format for each entry requiring a multi-line key instead
    * e.g. `defaultshader.frag.glsl` and `defaulshader.vert.glsl`
* Did you notice the error in the JSON fragment source?
   * `"    }",]` is invalid syntax since you got a , but not a following key
* YAML **forbids** tabs
  * you didn't see that we used 4 spaces instead of tabs? How dare you User touching our config!
* YAML seems to be more forgiving on quotation marks than TOML_

I'm too lazy to add a nested tree example now

**Comment by aschaeffer** [comment]
References can be supported by the configuration format or by code. During loading the data structure you can also resolve the references by id or by name. For example, a map references to other textures and models. But if each textures and model has it's own uuid and you can use the uuid as the reference. So for me support for references in the data format are not that important.

Next, I don't see any reason for wrapping shader source code in any other format. Shaders should go into their own files written in the shading language. GLSL can comments.

As you said, the meta information about the available shaders would go into its own data structure:

    {
        "shaders": [
            {
                "name": "default-shader",
                "description": "The default shader acts on the vertices (first stage)",
                "vertexSource": "media/shaders/default.vertex.glsl",
                "fragmentSource": "media/shaders/default.fragment.glsl"
            }, {
                ...
            }
        ],
        "fallbackShaders": [
            "notexture-shader",
            "null-shader"
        ]
    }

The problem I have with "configuration files" for "stuff content creators edit (e.g. model/texture/sound configurations)" is that in fact we want **structured data**. And the 90% of the content creators don't want to edit text files (in whatever format it may be) but use a user interface for this task. This is really only dump data, no scripting, no creativity.

* Define suitable data structures for the meta information of textures, models, sounds and so on
* Create a user interface for editing these data structures
* Use Drag'n'drop: if the user drops a picture file into the texture browser a new data structure is created and the texture editor appears where the content creator can edit the missing information
* Create an auto indexing script for detecting new models/textures/sounds
* The data structures can be loaded, saved and synchronized in the same way

For example for a texture meta information structure could be:

    {
        "uuid": "[uuid]",
        "name": "Space station floor (metal)",
        "description": "This textures is for metallic floors like in space stations",
        "tags": [ "metal", "floor", "bumpmap", "blue" ]
        "author": "Max Mustermann",
        "version": 10,
        "filename": "media/textures/[uuid]/10/texture.png",
        "normals": "media/textures/[uuid]/10/texture_n.png",
        "uv": "media/textures/[uuid]/10/texture_uv.png",
        "bump": "media/textures/[uuid]/10/texture_b.png",
    }

Keep it simple stupid.

For example a map could reference these textures by uuid and version:

    {
        "uuid": "[uuid]",
        "name": "pandora",
        "description": "Best map ever",
        "author": "Fatality",
        "version": 392,
        "textures": [
           {
               "uuid": "texture_uuid_1",
               "version": 10
           }, {
               "uuid": "texture_uuid_2",
               "version": -1
           }, {
               "uuid": "texture_uuid_3",
               "version": 6
           }, {
               ...
           }
        ]
    }

For playermodels: The animations would be in a separate file. In the playermodel configuration you reference to the animation file. This avoids copy and pasting and allows to versionize the animations.

We don't forbid to edit it by hand but it's just not the standard use case because 90% of the users use the user interface.

For me there are three use cases which are not data:

* settings which are required to get the application running at all (important screen and startup settings, media paths, ...)
* user preferences (mouse settings, ...)
* server side configuration (administration of the game server)

The users and administrators should be able to read and understand these files, it should be easy to edit (no complex syntax) and of course comments are essential. Also, users may share or publish their config files. For these TOML is way better than json.

**Comment by Croydon** [comment]
YAML is awfully complex. Please don't 😆 

JSON and/or TOML should be fine.

I agree with @aschaeffer JSON is better for data structures, while TOML would be better for settings.

Would it be a reasonable option to work with both?

**Comment by a-teammate** [comment]
Update: Since #354 is planned, we do not need any JSON/YAML/TOML handling on InexorCore side (C++ side) directly.

InexorCore is hence not involved in any filesystem operations regarding configurations. Only plain files are loaded there.
Any metainfo comes through the tree from InexorFlex

**Comment by Fohlen** [comment]
Since this is handled on the `flex` side, the structure will look as following

- we support a converter for `cfg` files which returns `tree` objects
- any configuration format, as desired, can easily provide a custom config format as a plugin, as long as it exports a `tree` object as well
- since I'll be implementing this functionality, I gave favor to implement a `toml` reference plugin

**Comment by aschaeffer** [comment]
@a-teammate -> @movabo suggested https://hjson.org/
