### ISSUE TITLE
Define the default ports (again)

### ISSUE THREAD

**Issue by aschaeffer** [inexor-game/code#367]
Follow up to #193 and #360

Because of the new architecture (Inexor Flex <-GRPC-> Inexor Core) and the possibility to run multiple instances (see #362) a typical Inexor installation uses multiple ports at the same time.

I would suggest these default ports:

| Component          | Provided Service     | Default Port | Protocol | Remarks |
| -------------------- | --------------------- | ------------- | -------- | --------- |
| Inexor Flex           | Webserver & REST  | 31416        | TCP      | |
| Inexor Core Client  | GRPC Server         | 31417        | TCP       | |
| Inexor Core Server | ENET Server          | 31415        | UDP      | see #193 |
| Inexor Core Server | GRPC Server         | 31414        | TCP       | = ENET-Server - 1 |

We should define the default port only for the default instances of the server and client.

**Comment by Fohlen** [comment]
Using `31415` for the default core instance with both, `gRPC` and `enet` is desirable..
In a sauerbraten-manner, expanding `31416` as the default flex port is most elegant, imho..
If we think that strategy won't fit us (because of performance, complexity, whatsoever..), using a iterative approach with `31415, 31416, 31417`, whereas the last is `flex` would probably suit as well..

**Comment by a-teammate** [comment]
We shouldnt rely on GRPC being tcp

**Comment by Fohlen** [comment]
I'll keep it `gRPC port` +1 for `server port`, since that is easier to remember for consequent instances of inexor. By that, `31417` shall be the standard definition for Flex.

**Comment by Fohlen** [comment]
Since this needs to be decided once Flex and Core roll out, following shall be noted.

- 31415 is the default `core` port (gRPC, TCP)
- 31416 is the default flex port (HTTP, TCP)
- 31417 is the default server port (enet, UDP)

This shall be due the nature that `31417` is not always needed, but  `31415, 31416` always are.

**Comment by Fohlen** [comment]
Any more discussion needed or can we draw a conclusion and make this a decision?

**Comment by Croydon** [comment]
Fine by me.

**Comment by Fohlen** [comment]
Changed due to consent. Updated in flex.

**Comment by aschaeffer** [comment]
We should add that information to the wiki, too.

**Comment by Fohlen** [comment]
Narf narf, can we close this?

**Comment by aschaeffer** [comment]
Yes
