### ISSUE TITLE
Give scripts access to the console

### ISSUE THREAD

**Issue by gitnyne** [inexor-game/code#60]
I was always missing something to catch game events/informations using pure CubeScript, so I suggest to give the sauerfork player full access to the console output for more CubeScript Power.

Example:

```

const char *line;

static hashtable<const char *, char *> warningsDisplayed;

void conoutfv(int type, const char *fmt, va_list args)
{
    static char buf[CONSTRLEN];
    vformatstring(buf, fmt, args, sizeof(buf));

    if(type == CON_WARN)
    {
        char **warning = warningsDisplayed.access(buf);
        if(warning == NULL)
        {
            char *newWarning = newstring(buf);
            warningsDisplayed[newWarning] = newWarning;
        }
        else return; 
    }

    conline(type, buf);
    filtertext(buf, buf);
    logoutf("%s", buf);
    line = buf;
}

ICOMMAND(getconline, "", (), result(line ? line : ""));
```

**Comment by IAmNotHanni** [comment]
Is this ticket still relevant? I think javascript will cover way more than this.

**Comment by Croydon** [comment]
@IAmNotHanni I think so. Until it is possible to do this with JavaScript it is not done.

**Comment by Fohlen** [comment]
This will be deprecated by #369

**Comment by aschaeffer** [comment]
Closed.

Even in this alpha stage the `Inexor Tree` and `Inexor Flex` are highly flexible in order to do dynamic tasks (not with cubescript but with javascript).

Besides from that, there is actually a ConsoleManager which manages a ring buffer for the console output of each `Inexor Core` instance. This ring buffer can be read. Maybe we can implement to spawn an event for each new console output line.
