### ISSUE TITLE
Crashes because failed assertion

### ISSUE THREAD

**Issue by koraa** [inexor-game/code#74]
reissen by SATAN!!!
game mode is coop edit
Cooperative Editing: Edit maps with multiple players simultaneously.
inexor: /home/karo/pr0j/sb/fork/code/src/shared/tools.h:622: T &vector<LightMapTexture>::operator[](int) [T = LightMapTexture]: Assertion `i>=0 && i<ulen' failed.
xargs: bin_linux/inexor: terminated by signal 6

**Comment by aschaeffer** [comment]
Confirmed, same here

**Comment by koraa** [comment]
thx :)

**Comment by koraa** [comment]
@killme recommends checking texture definitions.
Although, even if this is the underlying problem we should still fix the C++ code to deal with such instances.

**Comment by Croydon** [comment]
Same happens for example when you try to load with the current master build the map c_egypt of the data branch nooby/licensecleanup.

**Comment by Croydon** [comment]
Just happened to me again.

![unbenannt](https://cloud.githubusercontent.com/assets/1593194/6995286/46e980cc-db3e-11e4-902f-9077c5163398.PNG)

**Comment by aschaeffer** [comment]
Without testing, I think it has to do with a missing "\0" in cube2 "strings" in a multi-threaded environment.

**Comment by a-teammate** [comment]
hm no the error is thrown because of an array violation in the vector implementation. since its LightMapTexture its somewhere a violation of vector<LightmapTexture> lightmaptexs;

(e.g. by calling lightmaptexs[-1])

Though im not able to reproduce the error, so someone else may have more luck debugging it.

**Comment by DarkDeepBlue** [comment]
This is an off-by-one error.

The error occurs in inexor/engine/renderva.cpp:1070. The according function is changebatchtmus(). If one tries to load c_egypt, then lmid == 6. In line 1070 then lmid+1 is passed as an index to vector lightmaptexs, which has the size of 7. Because of that the assertion lmid<7 fails.

**Comment by killme** [comment]
Should be fixed with #244

**Comment by Croydon** [comment]
If I remember it correctly we wanted to let the bug open till we have fixed the underlying problem.
